version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3.9-alpine"
    ports:
      - "5672:5672"
    deploy: 
      mode: replicated
      replicas: 1
    volumes:
      - ./data/rabbitmq/:/var/lib/rabbitmq/  